image: ruby2.0.0
cache:
  - /tmp/bundler
script:
  - ls -la /tmp/bundler
  - cp config/database.yml.example config/database.yml
  - sudo chown -R ubuntu:ubuntu /tmp/bundler
  - sudo chmod -R ug+rw /tmp/bundler
  - bundle install --quiet --path /tmp/bundler
  - export TEST_DB_NAME= YAML::load(IO.read("config/database.yml"))['test']['database']
  - psql -c "create database %{TEST_DB_NAME};" -U postgres -h 127.0.0.1
  - bundle exec rake db:schema:load
  - bundle exec rspec spec
services:
  - postgres
notify:
  flowdock:
    token: "2d165fe8bdbac41933a9db3f36a24e9a"
    source: "CI"
    tags: "drone"
    on_started: false
    on_success: true
    on_failure: true