image: ruby2.0.0
cache:
  - /tmp/bundler
script:
  - ls -la /tmp/bundler
  - cp config/database.yml.example config/database.yml
  - sudo chown -R ubuntu:ubuntu /tmp/bundler
  - sudo chmod -R ug+rw /tmp/bundler
  - bundle install --quiet --path /tmp/bundler
  - psql -c 'create database test;' -U postgres -h 127.0.0.1
  - bundle exec rake db:schema:load
  - bundle exec rspec spec
services:
  - postgres
notify:
  email:
    recipients:
      - alan.haikal@kipusystems.com
    on_success: true
    on_failure: true